const assert=require('node:assert/strict');const {Game,STAGES}=require('../play/core.js');const DT=1/120;
const advance=(g,t,input={})=>{for(let i=0;i<t/DT;i++)g.step(DT,input)};
const g=new Game();g.hp=200;assert(g.heal());assert.equal(g.heals,2);assert.equal(g.hp,200);advance(g,.7);assert.equal(g.hp,500);assert(g.heal());g.player.invuln=0;g.hurt(300,900);advance(g,.7);assert.equal(g.hp,200);assert.equal(g.heals,1);g.hp=600;assert(!g.heal());assert.equal(g.heals,1);
g.player.x=610;g.player.y=585;g.interact();assert(g.resting);assert.equal(g.heals,3);const frozen=JSON.stringify([g.time,g.player.x,g.hp]);advance(g,1,{right:true,attack:true});assert.equal(JSON.stringify([g.time,g.player.x,g.hp]),frozen);assert(!g.travel('syrup','syrup-c'));g.closeRest();g.transition('syrup');assert.equal(g.stage,'sunny');
g.buggyDefeated=true;g.transition('syrup');assert.equal(g.stage,'syrup');g.player.x=260;g.interact();assert(g.resting);assert(g.travel('sunny','sunny'));assert.equal(g.stage,'sunny');assert(g.travel('syrup','syrup-a'));assert.equal(g.player.x,215);const copy=new Game(g.save());assert(copy.visited.some(v=>v.id==='syrup-a'));g.closeRest();g.transition('mansion');assert.equal(g.boss.kind,'kuro');g.player.x=300;g.player.invuln=999;const attacks=new Set();for(let i=0;i<1800;i++){g.step(DT);attacks.add(g.boss.attack);}assert(attacks.has('slash')&&attacks.has('feint')&&attacks.has('lunge'));g.boss.hp=50;for(let i=0;i<1600;i++){g.step(DT);attacks.add(g.boss.attack);}assert(attacks.has('flurry'));g.damageEnemy(g.boss,999,1);assert(g.kuroDefeated);assert.equal(new Game(g.save()).kuroDefeated,true);const reward=g.berries;g.player.x=880;g.player.y=430;g.interact();assert.equal(g.boss.hp,120);g.damageEnemy(g.boss,999,1);assert.equal(g.berries,reward);
for(let index=0;index<STAGES.syrup.platforms.length-1;index++){
 let reached=false;for(const setback of [20,45,75]){for(const dashAt of [-1,.22,.38,.52]){const t=new Game();t.buggyDefeated=true;t.loadStage('syrup');t.enemies=[];t.world={...t.world,hazards:[]};const from=t.world.platforms[index],next=t.world.platforms[index+1],p=t.player;Object.assign(p,{x:from.end-setback,y:from.y,vx:205,platform:from.id,grounded:true});for(let i=0;i<210;i++){const target=(next.x+next.end)/2;t.step(DT,{jump:i===0,up:true,right:p.x<target-8,left:p.x>target+8,dash:dashAt>=0&&i===Math.round(dashAt/DT)});if(p.grounded&&p.platform===next.id){reached=true;break;}}if(reached)break;}if(reached)break;}assert(reached,'Syrup route landing '+index);
}
console.log('PASS healing, interrupted heal, rest freeze, refill, discovered-only travel, save migration, chapter gate, Kuro phases/rematch/rewards and every Syrup platform landing');
